name: Deploy website to GitHub Pages

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  config:
    runs-on: ubuntu-latest
    outputs:
      deploy-host: ${{ steps.check.outputs.host }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: hugoblox.yaml
          sparse-checkout-cone-mode: false

      - name: Check deploy host
        id: check
        run: |
          echo "host=github-pages" >> $GITHUB_OUTPUT

  build:
    needs: config
    uses: ./.github/workflows/build.yml
    secrets: inherit

  deploy:
    needs: [config, build]
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          path: ./public

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
